[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
members = ["starkrs","stark-core","stark-provider"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
ethers = "2.0.4"